server:
  port: 8084

spring:
  application:
    name: page-service
  thymeleaf:
    cache: false # 关闭缓存
  rabbitmq:
    host: 111.230.104.64
    username: guest
    password: guest
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}.${server.port}

ly:
  thymeleaf:
    destPath: E:\User\data\item\html


